import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react';
import Link from 'next/link';
import { useSession } from 'next-auth/client';
import Navbar from '../components/Navbar';
import Profile from '../components/Profile';
import Calculator from '../components/Calculator';

export default function Home() {
    const [session, loading] = useSession();
    console.log(session)
    return (
        <div className={styles.container}>
            <Head>
                <title>My Care</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <Profile img={session ? session.user.image : 'profile.jpg'} />
            <Calculator />

            <footer className={styles.footer}>
                <a
                    href="https://github.com/lucascantao"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    github.com/lucascantao
  </a>
            </footer>
        </div>
    )
}
